<?php
    require_once(__DIR__ . "./../components/header.phtml");
?>

<body>
  <div class="container mb-5">
    <h2>Register</h2>
    <form action="/login" method="POST">
    <div class="form-group">
        <label for="name">Nome:</label>
        <input type="name" class="form-control" id="name" placeholder="Insira o seu nome" name="name">
      </div>
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" placeholder="Digite seu email" name="email">
      </div>
      <div class="form-group">
        <label for="senha">Senha:</label>
        <input type="password" class="form-control" id="password" placeholder="Insira sua senha" name="senha">
      </div>
      <div class="form-group">
        <label for="cpf">CPF:</label>
        <input type="cpf" class="form-control" id="password" placeholder="Insira seu CPF" name="cpf">
      </div>
      <button type="submit" class="btn btn-register" style="background-color: #2F4F4F; color: white;">Registrar</button>
    </form>
  </div>

<?php
    require(__DIR__ . "./../components/footer.phtml");
?>

</body>